#!/usr/bin/env python3
"""
Regenerate the org ERD index table on the central docs page — so the "every DB repo's data model is
surfaced here" standard is AUTO-maintained, never hand-curated (schema-erd.md canonical surface).

What it does: enumerate every non-archived repo in the org, read its git tree ONCE, and for any repo
that commits a tbls ERD (`docs/data-model/` or `backend/docs/data-model/`) emit a row — repo · inferred
migration toolchain · table count · a link to the committed README.md (GitHub renders the Mermaid). A
dbt repo (has `dbt/dbt_project.yml`, no migration-owned schema) is emitted as the documented carve-out.
The table is written between the ERD-INDEX markers on the page; everything else is left untouched.

Run: `python3 scripts/gen-erd-index.py` (needs `gh` authenticated). CI runs it + opens a PR on drift
(.github/workflows/update-erd-index.yml). No manual per-service step → a new DB repo appears on its own.
"""
from __future__ import annotations
import json
import subprocess
import sys
from pathlib import Path

ORG = "andrelair-platform"
PAGE = Path(__file__).resolve().parent.parent / "docs" / "insurance-platform" / "schema-erd-autogenerated.md"
START, END = "{/* ERD-INDEX:START */}", "{/* ERD-INDEX:END */}"


def gh_json(args: list[str]):
    out = subprocess.run(["gh", *args], capture_output=True, text=True)
    if out.returncode != 0:
        return None
    try:
        return json.loads(out.stdout)
    except json.JSONDecodeError:
        return None


def repo_tree(repo: str) -> list[str]:
    """All committed paths in the default branch (one API call); [] if unreadable/truncated-empty."""
    data = gh_json(["api", f"repos/{ORG}/{repo}/git/trees/HEAD?recursive=1"])
    if not data or "tree" not in data:
        return []
    return [e["path"] for e in data["tree"] if e.get("type") in ("blob", "tree")]


def infer_toolchain(paths: set[str], blobs: list[str]) -> str:
    """Disambiguated by marker files — order matters (Drizzle+golang-migrate both use db/migrations)."""
    if any(p in paths for p in ("drizzle.config.js", "drizzle.config.ts")):
        return "Drizzle"
    if "alembic.ini" in paths:
        return "Alembic"
    if "src/main/resources/db/migration" in paths or any(
        b.startswith("src/main/resources/db/migration/") for b in blobs
    ):
        return "Flyway"
    if "backend/src/database/migrations" in paths or any(
        b.startswith("backend/src/database/migrations/") for b in blobs
    ):
        return "TypeORM"
    if any(b.startswith("db/migrations/") and b.endswith(".up.sql") for b in blobs):
        return "golang-migrate"
    return "—"


def main() -> int:
    repos = gh_json(["repo", "list", ORG, "--limit", "300", "--json", "name,isArchived"]) or []
    rows: list[tuple[str, str, str, str]] = []  # (repo, toolchain, tables, link-md)
    dbt_rows: list[str] = []

    for r in sorted(repos, key=lambda x: x["name"]):
        if r.get("isArchived"):
            continue
        name = r["name"]
        blobs = repo_tree(name)
        if not blobs:
            continue
        paths = set(blobs)

        # a dbt repo with no migration-owned schema = the documented carve-out
        is_dbt = "dbt/dbt_project.yml" in paths
        dm_path = None
        for cand in ("docs/data-model", "backend/docs/data-model"):
            if f"{cand}/README.md" in paths:
                dm_path = cand
                break

        if dm_path:
            tables = sum(
                1
                for b in blobs
                if b.startswith(f"{dm_path}/")
                and b.endswith(".md")
                and not b.rsplit("/", 1)[-1].lower().startswith("readme")
            )
            link = f"[{dm_path}](https://github.com/{ORG}/{name}/blob/main/{dm_path}/README.md)"
            rows.append((name, infer_toolchain(paths, blobs), str(tables or "—"), link))
        elif is_dbt:
            dbt_rows.append(
                f"| {name} | **dbt (carve-out)** | — | self-documented by committed dbt "
                f"**model contracts** (`models/**/_*.yml`) + CI `dbt parse` — tbls is the wrong tool "
                f"for a *derived* warehouse (not a migration-owned schema) |"
            )

    if not rows:
        print("no repos with a committed docs/data-model found — aborting (likely a gh/auth issue)", file=sys.stderr)
        return 1

    header = "| Repo | Migration toolchain | Tables | Committed ERD |\n|---|---|---:|---|"
    body = [f"| {n} | {tc} | {t} | {link} |" for (n, tc, t, link) in rows] + dbt_rows
    table = "\n".join([header, *body])

    text = PAGE.read_text()
    if START not in text or END not in text:
        print(f"markers {START}/{END} not found in {PAGE}", file=sys.stderr)
        return 1
    pre, rest = text.split(START, 1)
    _, post = rest.split(END, 1)
    new = f"{pre}{START}\n{table}\n{END}{post}"
    if new != text:
        PAGE.write_text(new)
        print(f"updated ERD index: {len(rows)} tbls repo(s) + {len(dbt_rows)} dbt carve-out(s)")
    else:
        print("ERD index already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
